In [1]:
import numpy as np
x=np.array([1,2,3,4,5,6])
print(type(x))


<class 'numpy.ndarray'>


In [2]:
print(x)

[1 2 3 4 5 6]


In [3]:
x=np.array([1,2,3,'n',5,6])

In [4]:
print(x)

['1' '2' '3' 'n' '5' '6']


In [9]:
a=np.linspace(start=0,stop=10,num=15,endpoint=True,retstep=False)

In [10]:
print(a)

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [11]:
a=np.linspace(start=0,stop=10,num=15,endpoint=True,retstep=True)//retstep is the increment eachtime
print(a)

(array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ]), 0.7142857142857143)


In [12]:
a=np.linspace(0,10,15,True,True)

In [13]:
print(a)

(array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ]), 0.7142857142857143)


In [15]:
s=np.arange(1,10,2)

In [16]:
print(s)

[1 3 5 7 9]


In [21]:
np.ones((3,4))#syntax:numpy.ones(shape,dtype) #default dtype+float 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.zeros((3,4),int) #to make it int specify dtype when creating

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [27]:
np.random.rand((5))#randomly generates 5 values

array([0.50487918, 0.1153028 , 0.35150207, 0.48236678, 0.68575616])

In [28]:
np.random.rand(5,2)#random array with 5 rows and 2 coloumns

array([[0.32915677, 0.72959012],
       [0.26125364, 0.97970483],
       [0.06688718, 0.97340781],
       [0.38859694, 0.04227347],
       [0.91639934, 0.11392573]])

In [29]:
np.logspace(1,10,num=5,endpoint=True,base=10.0) #syntax: np.logspace(start,stop,num,endpoint,base)

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

In [47]:
#
import timeit
x=range(1000)


In [34]:
print(x)

range(0, 1000)


In [35]:
y=np.array(x)

In [40]:
print(x)

range(0, 1000)


In [42]:
import sys
sys.getsizeof(x)#for single elememt in list

48

In [44]:
sys.getsizeof(1)*len(x)#sixe of entire list

28000

In [45]:
sys.getsizeof(1)*len(y)

28000

In [48]:
grid=np.arange(1,10).reshape(3,3)#reshaping the array 3x3

In [49]:
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [51]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
a.shape # arrayname.shape gives the dimensions of the array

(3, 3)

In [54]:
np.add(grid,a) #add the arrays (grid,a) elementwise

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [55]:
np.multiply(grid,a)  # multipllies the arrays (grid,a) elementwises

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [59]:
np.subtract(grid,a) #subraction elementwise

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [60]:
np.divide(grid,a) #division elementwise

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
np.remainder(grid,a) #remainder when elementwise division

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [62]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [65]:
a[-1][-1]

9

In [66]:
a[0][1] #index starts from 0

2

In [67]:
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
a[:,0] #access column wise

array([1, 4, 7])

In [69]:
a[0,:] #access row wise

array([1, 2, 3])

In [70]:
a_sum=a[:2,:2]  #subarray from array(a)

In [71]:
print(a_sum)

[[1 2]
 [4 5]]


In [72]:
a_sum[0][0]=11 #modifing the subarray element

In [73]:
print(a_sum)

[[11  2]
 [ 4  5]]


In [74]:
0print(a) #modifying the sbarray will automatically modify the original array as well see a[0][0]=11 instead of 1

[[11  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [75]:
 np.transpose(a) #transposing the array rows to cols ....

array([[11,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9]])

In [77]:
np.append(a,[[10,11,12]],axis=0) #axis=0 row wise adds

array([[11,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [84]:
col=np.array([13,14,15]).reshape(3,1) #reshaping into coloumns

In [85]:
np.append(a,col,axis=1) #adding coloumnwise after reshaping

array([[11,  2,  3, 13],
       [ 4,  5,  6, 14],
       [ 7,  8,  9, 15]])

In [95]:
np.insert(a,1,[90,80,70],axis=0)


array([[11,  2,  3],
       [90, 80, 70],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [96]:
np.delete(a,2,axis=0) #delete third roww

array([[11,  2,  3],
       [ 4,  5,  6]])

In [ ]:
#MATRICES 2D data structure of rows and coloumns syntax:numpy.matrix(data)

In [98]:
a=np.matrix("1,2,3,4;4,5,6,7;7,8,9,10") #;-indicates end of that col

In [99]:
print(a)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [101]:
a.shape #shape gives the order of matrix no of rows and coloumns

(3, 4)

In [102]:
a.shape[0] #0-indicates no of rows

3

In [103]:
a.shape[1] #1-indicates no of cols

4

In [104]:
a.size #total elements in matrix

12

In [107]:
np.insert(a,0,[11,22,33,44],axis=0) #at which position we have t0 insert this 

matrix([[11, 22, 33, 44],
        [ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]])

In [108]:
print(a)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [110]:
a[1,2]=-3 #modifying 1-row 2-col

In [111]:
print(a)

[[ 1  2  3  4]
 [ 4  5 -3  7]
 [ 7  8  9 10]]


In [115]:
print(a[1,:]) # extracting elents of 2 row

[[ 4  5 -3  7]]


In [116]:
print(a[:,2]) #extracting elements of 3 coloums

[[ 3]
 [-3]
 [ 9]]


In [117]:
b=np.matrix("11,22,33,44;44,55,66,77;77,88,99,90")

In [118]:
print(b)

[[11 22 33 44]
 [44 55 66 77]
 [77 88 99 90]]


In [119]:
print(np.add(a,b)) #addition of a,b matrices

[[ 12  24  36  48]
 [ 48  60  63  84]
 [ 84  96 108 100]]


In [120]:
print(np.subtract(a,b))

[[-10 -20 -30 -40]
 [-40 -50 -69 -70]
 [-70 -80 -90 -80]]


In [122]:
print(a,b)

[[ 1  2  3  4]
 [ 4  5 -3  7]
 [ 7  8  9 10]] [[11 22 33 44]
 [44 55 66 77]
 [77 88 99 90]]


In [124]:
a=np.insert(a,3,[23,34,45,56],axis=0)

In [125]:
print(a)

[[ 1  2  3  4]
 [ 4  5 -3  7]
 [ 7  8  9 10]
 [23 34 45 56]]


In [126]:
b=np.insert(b,3,[93,37,41,96],axis=0)

In [127]:
print(b)

[[11 22 33 44]
 [44 55 66 77]
 [77 88 99 90]
 [93 37 41 96]]


In [128]:
np.dot(a,b) #matric multuplivcation of a,b usses np.dot(a,b)

matrix([[  702,   544,   626,   852],
        [  684,   358,   452,   963],
        [ 2052,  1756,  2060,  2694],
        [10422,  8408,  9754, 13056]])

In [129]:
b=np.transpose(b) #matrix mul after transposing b

In [130]:
np.dot(a,b)

matrix([[  330,   660,   910,   674],
        [  363,   792,  1081,  1106],
        [  990,  2112,  3034,  2276],
        [ 4950, 10164, 14258, 10618]])

In [131]:
np.multiply(a,b) #element wise multuplication 

matrix([[  11,   88,  231,  372],
        [  88,  275, -264,  259],
        [ 231,  528,  891,  410],
        [1012, 2618, 4050, 5376]])

In [133]:
np.divide(a,b) #element wise division

matrix([[ 0.09090909,  0.04545455,  0.03896104,  0.04301075],
        [ 0.18181818,  0.09090909, -0.03409091,  0.18918919],
        [ 0.21212121,  0.12121212,  0.09090909,  0.24390244],
        [ 0.52272727,  0.44155844,  0.5       ,  0.58333333]])